# Generated by Django 5.2.7 on 2025-11-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_salestransaction_payment_method_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Product expiration date', null=True),
        ),
    ]
