# Generated by Django 5.2.7 on 2025-11-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived products are hidden from normal view but can be restored'),
        ),
    ]
